// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contentunderstanding$0 from "../contentunderstanding/models.js";

export function GetResult(jobID: string): $CancellablePromise<contentunderstanding$0.AnalysisResult> {
    return $Call.ByID(2728044300, jobID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PollResult(operationLocation: string): $CancellablePromise<contentunderstanding$0.AnalysisResult> {
    return $Call.ByID(3737886187, operationLocation).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(): $CancellablePromise<contentunderstanding$0.ServiceStatus> {
    return $Call.ByID(257883141).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Submit(asset: contentunderstanding$0.VideoAsset): $CancellablePromise<string> {
    return $Call.ByID(3680567075, asset);
}

// Private type creation functions
const $$createType0 = contentunderstanding$0.AnalysisResult.createFrom;
const $$createType1 = contentunderstanding$0.ServiceStatus.createFrom;
