// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editing$0 from "../editing/models.js";

export function CancelRender(jobID: string): $CancellablePromise<editing$0.RenderJob | null> {
    return $Call.ByID(2725404402, jobID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateDraftProject(name: string): $CancellablePromise<editing$0.EditProject> {
    return $Call.ByID(2469632424, name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(3833426788, projectID);
}

export function ListProjects(): $CancellablePromise<editing$0.EditProject[]> {
    return $Call.ByID(3962621678).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Render submits an asynchronous render job, polls it with the Wails call
 * context, streams the completed output to a scoped temp file, and publishes it
 * to OneDrive with the desktop delegated identity.
 */
export function Render(projectID: string): $CancellablePromise<editing$0.RenderJob | null> {
    return $Call.ByID(2403669932, projectID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RenderJob returns the current state of a render job.
 */
export function RenderJob(jobID: string): $CancellablePromise<editing$0.RenderJob | null> {
    return $Call.ByID(916506303, jobID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RenderJobs returns all render jobs.
 */
export function RenderJobs(): $CancellablePromise<(editing$0.RenderJob | null)[]> {
    return $Call.ByID(3407409956).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SaveProject(project: editing$0.EditProject): $CancellablePromise<editing$0.EditProject> {
    return $Call.ByID(2743046994, project).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = editing$0.RenderJob.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = editing$0.EditProject.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
