// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editing$0 from "../editing/models.js";

export function CreateDraftProject(name: string): $CancellablePromise<editing$0.EditProject> {
    return $Call.ByID(2469632424, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListProjects(): $CancellablePromise<editing$0.EditProject[]> {
    return $Call.ByID(3962621678).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveProject(project: editing$0.EditProject): $CancellablePromise<editing$0.EditProject> {
    return $Call.ByID(2743046994, project).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = editing$0.EditProject.createFrom;
const $$createType1 = $Create.Array($$createType0);
