// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as videoindexerstudio$0 from "../videoindexerstudio/models.js";

export class AppOverview {
    "name": string;
    "version": string;
    "startedAt": string;
    "description": string;

    /** Creates a new AppOverview instance. */
    constructor($$source: Partial<AppOverview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): AppOverview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppOverview($$parsedSource as Partial<AppOverview>);
    }
}

/**
 * EditingCapabilities describes the editing operations and media evidence the
 * desktop can safely present. It intentionally exposes readiness, never secrets.
 */
export class EditingCapabilities {
    "projectPersistence": boolean;
    "eligibleAssetCount": number;
    "renderServiceReady": boolean;
    "oneDriveReady": boolean;
    "renderReady": boolean;
    "renderRecoveryMessage"?: string;
    "supportedRenderPresets": string[];
    "maximumRenderClips": number;
    "orderedVideoClips": boolean;
    "cutTransitions": boolean;
    "renderProgress": boolean;
    "renderCancellation": boolean;
    "manualClipAddition": boolean;
    "clipRemoval": boolean;
    "clipReordering": boolean;
    "trimming": boolean;
    "mediaMetadata": boolean;
    "thumbnails": boolean;
    "preview": boolean;
    "titles": boolean;
    "audio": boolean;
    "multiTrack": boolean;

    /** Creates a new EditingCapabilities instance. */
    constructor($$source: Partial<EditingCapabilities> = {}) {
        if (!("projectPersistence" in $$source)) {
            this["projectPersistence"] = false;
        }
        if (!("eligibleAssetCount" in $$source)) {
            this["eligibleAssetCount"] = 0;
        }
        if (!("renderServiceReady" in $$source)) {
            this["renderServiceReady"] = false;
        }
        if (!("oneDriveReady" in $$source)) {
            this["oneDriveReady"] = false;
        }
        if (!("renderReady" in $$source)) {
            this["renderReady"] = false;
        }
        if (!("supportedRenderPresets" in $$source)) {
            this["supportedRenderPresets"] = [];
        }
        if (!("maximumRenderClips" in $$source)) {
            this["maximumRenderClips"] = 0;
        }
        if (!("orderedVideoClips" in $$source)) {
            this["orderedVideoClips"] = false;
        }
        if (!("cutTransitions" in $$source)) {
            this["cutTransitions"] = false;
        }
        if (!("renderProgress" in $$source)) {
            this["renderProgress"] = false;
        }
        if (!("renderCancellation" in $$source)) {
            this["renderCancellation"] = false;
        }
        if (!("manualClipAddition" in $$source)) {
            this["manualClipAddition"] = false;
        }
        if (!("clipRemoval" in $$source)) {
            this["clipRemoval"] = false;
        }
        if (!("clipReordering" in $$source)) {
            this["clipReordering"] = false;
        }
        if (!("trimming" in $$source)) {
            this["trimming"] = false;
        }
        if (!("mediaMetadata" in $$source)) {
            this["mediaMetadata"] = false;
        }
        if (!("thumbnails" in $$source)) {
            this["thumbnails"] = false;
        }
        if (!("preview" in $$source)) {
            this["preview"] = false;
        }
        if (!("titles" in $$source)) {
            this["titles"] = false;
        }
        if (!("audio" in $$source)) {
            this["audio"] = false;
        }
        if (!("multiTrack" in $$source)) {
            this["multiTrack"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditingCapabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): EditingCapabilities {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supportedRenderPresets" in $$parsedSource) {
            $$parsedSource["supportedRenderPresets"] = $$createField6_0($$parsedSource["supportedRenderPresets"]);
        }
        return new EditingCapabilities($$parsedSource as Partial<EditingCapabilities>);
    }
}

export class ProtectedEndpointStatus {
    "configured": boolean;
    "endpoint"?: string;
    "hasApiKey": boolean;
    "message": string;

    /** Creates a new ProtectedEndpointStatus instance. */
    constructor($$source: Partial<ProtectedEndpointStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("hasApiKey" in $$source)) {
            this["hasApiKey"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtectedEndpointStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtectedEndpointStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtectedEndpointStatus($$parsedSource as Partial<ProtectedEndpointStatus>);
    }
}

export class VideoIndexerStudioJob {
    "id": string;
    "assetId": string;
    "assetIds"?: string[];
    "assetName": string;
    "composition"?: boolean;
    "dependencyJobIds"?: string[];
    "remoteJobId"?: string;
    "remoteStatus"?: string;
    "stage"?: string;
    "status": string;
    "errorMessage"?: string;
    "retryable"?: boolean;
    "suggestionId"?: string;
    "projectId"?: string;
    "videoIndexerVideoId"?: string;
    "videoIndexResult"?: videoindexerstudio$0.VideoIndexResult | null;
    "editPlan"?: videoindexerstudio$0.EditPlan | null;
    "timelineDrafts"?: videoindexerstudio$0.TimelineDraft[];
    "checkpoints"?: videoindexerstudio$0.JobCheckpoint[];
    "createdAt": string;
    "updatedAt": string;
    "startedAt"?: string | null;
    "completedAt"?: string | null;
    "claimedBy"?: string;

    /** Creates a new VideoIndexerStudioJob instance. */
    constructor($$source: Partial<VideoIndexerStudioJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("assetId" in $$source)) {
            this["assetId"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexerStudioJob instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexerStudioJob {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType4;
        const $$createField17_0 = $$createType6;
        const $$createField18_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assetIds" in $$parsedSource) {
            $$parsedSource["assetIds"] = $$createField2_0($$parsedSource["assetIds"]);
        }
        if ("dependencyJobIds" in $$parsedSource) {
            $$parsedSource["dependencyJobIds"] = $$createField5_0($$parsedSource["dependencyJobIds"]);
        }
        if ("videoIndexResult" in $$parsedSource) {
            $$parsedSource["videoIndexResult"] = $$createField15_0($$parsedSource["videoIndexResult"]);
        }
        if ("editPlan" in $$parsedSource) {
            $$parsedSource["editPlan"] = $$createField16_0($$parsedSource["editPlan"]);
        }
        if ("timelineDrafts" in $$parsedSource) {
            $$parsedSource["timelineDrafts"] = $$createField17_0($$parsedSource["timelineDrafts"]);
        }
        if ("checkpoints" in $$parsedSource) {
            $$parsedSource["checkpoints"] = $$createField18_0($$parsedSource["checkpoints"]);
        }
        return new VideoIndexerStudioJob($$parsedSource as Partial<VideoIndexerStudioJob>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = videoindexerstudio$0.VideoIndexResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = videoindexerstudio$0.EditPlan.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = videoindexerstudio$0.TimelineDraft.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = videoindexerstudio$0.JobCheckpoint.createFrom;
const $$createType8 = $Create.Array($$createType7);
