// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onedrive$0 from "../onedrive/models.js";

/**
 * AccessToken implements onedrive.TokenProvider.
 */
export function AccessToken(scopes: string[]): $CancellablePromise<string> {
    return $Call.ByID(411057365, scopes);
}

export function CreateUploadSession(destinationPath: string, fileSizeBytes: number): $CancellablePromise<onedrive$0.OneDriveUploadSession> {
    return $Call.ByID(562500289, destinationPath, fileSizeBytes).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DriveClient returns a configured onedrive.Client that can be used for
 * non-upload Graph operations like listing folder contents. It shares the
 * same token provider (and cache) as the upload methods.
 */
export function DriveClient(): $CancellablePromise<onedrive$0.Client | null> {
    return $Call.ByID(232748345).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PollDeviceCodeAuth(): $CancellablePromise<onedrive$0.AuthState> {
    return $Call.ByID(3065570346).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(3941931845);
}

export function StartDeviceCodeAuth(): $CancellablePromise<onedrive$0.DeviceCodeSession> {
    return $Call.ByID(927179351).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Status(): $CancellablePromise<onedrive$0.Status> {
    return $Call.ByID(497750632).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = onedrive$0.OneDriveUploadSession.createFrom;
const $$createType1 = onedrive$0.Client.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = onedrive$0.AuthState.createFrom;
const $$createType4 = onedrive$0.DeviceCodeSession.createFrom;
const $$createType5 = onedrive$0.Status.createFrom;
