// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contentunderstanding$0 from "../contentunderstanding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

export function AddAsset(asset: library$0.ProjectAsset): $CancellablePromise<void> {
    return $Call.ByID(1000603399, asset);
}

/**
 * AnalysisJobs returns all analysis jobs, ordered by creation time
 * (newest first).
 */
export function AnalysisJobs(): $CancellablePromise<library$0.AnalysisJob[]> {
    return $Call.ByID(860486112).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AnalysisResult returns the analysis result for a job, or nil if the job is
 * still running, failed, or has not yet produced a result.
 */
export function AnalysisResult(jobID: string): $CancellablePromise<contentunderstanding$0.AnalysisResult | null> {
    return $Call.ByID(3471946201, jobID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Current(): $CancellablePromise<library$0.ProjectLibrary> {
    return $Call.ByID(1949001123).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAssetAnalysis returns the most recent analysis job for an asset, or nil
 * if the asset has never been submitted for analysis.
 */
export function GetAssetAnalysis(assetID: string): $CancellablePromise<library$0.AnalysisJob | null> {
    return $Call.ByID(3236891816, assetID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListAssets(): $CancellablePromise<library$0.ProjectAsset[]> {
    return $Call.ByID(3117580363).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SubmitForAnalysis starts an Azure Content Understanding analysis for the
 * given asset. It creates a OneDrive shareable link, submits it to CU, and
 * begins async polling in the background. Progress is reported via the
 * 'analysis:progress' and 'analysis:completed' Wails events, in addition to
 * being persisted so AnalysisJobs/AnalysisResult reflect the latest state.
 */
export function SubmitForAnalysis(assetID: string): $CancellablePromise<library$0.AnalysisJob | null> {
    return $Call.ByID(2063292583, assetID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SyncWithOneDrive scans the configured OneDrive folder and registers any
 * assets that are not yet in the local store. It returns the number of new
 * assets discovered. This is idempotent — duplicates are skipped by DriveItemID.
 */
export function SyncWithOneDrive(folderPath: string): $CancellablePromise<number> {
    return $Call.ByID(2098039341, folderPath);
}

// Private type creation functions
const $$createType0 = library$0.AnalysisJob.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = contentunderstanding$0.AnalysisResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = library$0.ProjectLibrary.createFrom;
const $$createType5 = $Create.Nullable($$createType0);
const $$createType6 = library$0.ProjectAsset.createFrom;
const $$createType7 = $Create.Array($$createType6);
