// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Get(): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(2586417217).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetMediaServiceEndpoint returns the currently configured Media Service
 * endpoint. The API key is intentionally never returned since it is
 * json:"-" and must not be exposed to the frontend.
 */
export function GetMediaServiceEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(2224009239);
}

export function GetMediaServiceStatus(): $CancellablePromise<$models.ProtectedEndpointStatus> {
    return $Call.ByID(1323579772).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetVideoIndexerServiceEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(1690227955);
}

export function GetVideoIndexerServiceStatus(): $CancellablePromise<$models.ProtectedEndpointStatus> {
    return $Call.ByID(1524802704).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Save(next: settings$0.AppSettings): $CancellablePromise<settings$0.AppSettings> {
    return $Call.ByID(1338747394, next).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetMediaServiceEndpoint saves the Media Service endpoint and, optionally, a
 * new API key. The API key is passed separately from AppSettings because the
 * field is json:"-" and never round-trips through Get/Save. Passing an empty
 * apiKey leaves the previously stored key untouched.
 */
export function SetMediaServiceEndpoint(endpoint: string, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(2621727267, endpoint, apiKey);
}

export function SetVideoIndexerServiceEndpoint(endpoint: string, apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(85403167, endpoint, apiKey);
}

// Private type creation functions
const $$createType0 = settings$0.AppSettings.createFrom;
const $$createType1 = $models.ProtectedEndpointStatus.createFrom;
