// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transfer$0 from "../transfer/models.js";

export function Cancel(jobID: string): $CancellablePromise<void> {
    return $Call.ByID(4290683839, jobID);
}

export function DescribeLocalFiles(req: transfer$0.DescribeLocalFilesRequest): $CancellablePromise<transfer$0.LocalMediaFile[]> {
    return $Call.ByID(891279966, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListJobs(): $CancellablePromise<transfer$0.TransferJob[]> {
    return $Call.ByID(3431541573).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartCameraToOneDrive(req: transfer$0.StartTransferRequest): $CancellablePromise<transfer$0.TransferJob> {
    return $Call.ByID(1711329853, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function StartLocalToOneDrive(req: transfer$0.LocalToOneDriveRequest): $CancellablePromise<transfer$0.TransferJob> {
    return $Call.ByID(2809690311, req).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = transfer$0.LocalMediaFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = transfer$0.TransferJob.createFrom;
const $$createType3 = $Create.Array($$createType2);
