// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as editing$0 from "../editing/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelIndexing(jobID: string): $CancellablePromise<$models.VideoIndexerStudioJob | null> {
    return $Call.ByID(3468323472, jobID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateEditProject(jobID: string, suggestionID: string): $CancellablePromise<editing$0.EditProject> {
    return $Call.ByID(2417067535, jobID, suggestionID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GenerateMultiVideoEdit creates one persistent composition that waits for or reuses source analyses.
 */
export function GenerateMultiVideoEdit(assetIDs: string[]): $CancellablePromise<$models.VideoIndexerStudioJob | null> {
    return $Call.ByID(1856538873, assetIDs).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GenerateMultiVideoEditWithIntent creates one persistent composition with an
 * optional editorial preference for grounded Azure narrative ranking.
 */
export function GenerateMultiVideoEditWithIntent(assetIDs: string[], narrativeIntent: string): $CancellablePromise<$models.VideoIndexerStudioJob | null> {
    return $Call.ByID(1974639139, assetIDs, narrativeIntent).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IndexingJob(jobID: string): $CancellablePromise<$models.VideoIndexerStudioJob | null> {
    return $Call.ByID(2037013561, jobID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IndexingJobs(): $CancellablePromise<$models.VideoIndexerStudioJob[]> {
    return $Call.ByID(1819232382).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SubmitForIndexing(assetID: string): $CancellablePromise<$models.VideoIndexerStudioJob | null> {
    return $Call.ByID(873605893, assetID).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.VideoIndexerStudioJob.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = editing$0.EditProject.createFrom;
const $$createType3 = $Create.Array($$createType0);
