// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as videoprocessing$0 from "../videoprocessing/models.js";

export function CompareBindings(): $CancellablePromise<videoprocessing$0.BindingEvaluation[]> {
    return $Call.ByID(3491719077).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Probe(input: string): $CancellablePromise<videoprocessing$0.ProbeResult> {
    return $Call.ByID(338432622, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Render(req: videoprocessing$0.RenderRequest): $CancellablePromise<videoprocessing$0.RenderJob> {
    return $Call.ByID(2433459356, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function RuntimeStatus(): $CancellablePromise<videoprocessing$0.RuntimeStatus> {
    return $Call.ByID(1337232034).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Thumbnail(req: videoprocessing$0.ThumbnailRequest): $CancellablePromise<void> {
    return $Call.ByID(483055608, req);
}

// Private type creation functions
const $$createType0 = videoprocessing$0.BindingEvaluation.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = videoprocessing$0.ProbeResult.createFrom;
const $$createType3 = videoprocessing$0.RenderJob.createFrom;
const $$createType4 = videoprocessing$0.RuntimeStatus.createFrom;
