// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AnalysisResult {
    "asset": VideoAsset;
    "jobId"?: string;
    "status"?: string;
    "scenes": Scene[];
    "transcript": TranscriptSegment[];
    "highlights": HighlightCandidate[];
    "suggestions": EditSuggestion[];

    /** Creates a new AnalysisResult instance. */
    constructor($$source: Partial<AnalysisResult> = {}) {
        if (!("asset" in $$source)) {
            this["asset"] = (new VideoAsset());
        }
        if (!("scenes" in $$source)) {
            this["scenes"] = [];
        }
        if (!("transcript" in $$source)) {
            this["transcript"] = [];
        }
        if (!("highlights" in $$source)) {
            this["highlights"] = [];
        }
        if (!("suggestions" in $$source)) {
            this["suggestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalysisResult {
        const $$createField0_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("asset" in $$parsedSource) {
            $$parsedSource["asset"] = $$createField0_0($$parsedSource["asset"]);
        }
        if ("scenes" in $$parsedSource) {
            $$parsedSource["scenes"] = $$createField3_0($$parsedSource["scenes"]);
        }
        if ("transcript" in $$parsedSource) {
            $$parsedSource["transcript"] = $$createField4_0($$parsedSource["transcript"]);
        }
        if ("highlights" in $$parsedSource) {
            $$parsedSource["highlights"] = $$createField5_0($$parsedSource["highlights"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField6_0($$parsedSource["suggestions"]);
        }
        return new AnalysisResult($$parsedSource as Partial<AnalysisResult>);
    }
}

export class Config {
    "endpoint": string;
    "analyzerId": string;
    "apiVersion": string;
    "sourceMode": string;
    "pollIntervalMs"?: number;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("analyzerId" in $$source)) {
            this["analyzerId"] = "";
        }
        if (!("apiVersion" in $$source)) {
            this["apiVersion"] = "";
        }
        if (!("sourceMode" in $$source)) {
            this["sourceMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}

export class EditSuggestion {
    "id": string;
    "title": string;
    "description": string;
    "sceneIds": string[];

    /** Creates a new EditSuggestion instance. */
    constructor($$source: Partial<EditSuggestion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sceneIds" in $$source)) {
            this["sceneIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): EditSuggestion {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sceneIds" in $$parsedSource) {
            $$parsedSource["sceneIds"] = $$createField3_0($$parsedSource["sceneIds"]);
        }
        return new EditSuggestion($$parsedSource as Partial<EditSuggestion>);
    }
}

export class HighlightCandidate {
    "id": string;
    "startMs": number;
    "endMs": number;
    "reason": string;
    "score": number;

    /** Creates a new HighlightCandidate instance. */
    constructor($$source: Partial<HighlightCandidate> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HighlightCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): HighlightCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HighlightCandidate($$parsedSource as Partial<HighlightCandidate>);
    }
}

export class Scene {
    "id": string;
    "startMs": number;
    "endMs": number;
    "labels": string[];
    "summary"?: string;
    "highlight": boolean;

    /** Creates a new Scene instance. */
    constructor($$source: Partial<Scene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("highlight" in $$source)) {
            this["highlight"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scene instance from a string or object.
     */
    static createFrom($$source: any = {}): Scene {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField3_0($$parsedSource["labels"]);
        }
        return new Scene($$parsedSource as Partial<Scene>);
    }
}

export class ServiceStatus {
    "configured": boolean;
    "endpoint"?: string;
    "analyzerId"?: string;
    "apiVersion"?: string;
    "sourceMode"?: string;
    "message": string;

    /** Creates a new ServiceStatus instance. */
    constructor($$source: Partial<ServiceStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceStatus($$parsedSource as Partial<ServiceStatus>);
    }
}

export class TranscriptSegment {
    "startMs": number;
    "endMs": number;
    "text": string;
    "speaker"?: string;
    "score"?: number;

    /** Creates a new TranscriptSegment instance. */
    constructor($$source: Partial<TranscriptSegment> = {}) {
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranscriptSegment instance from a string or object.
     */
    static createFrom($$source: any = {}): TranscriptSegment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranscriptSegment($$parsedSource as Partial<TranscriptSegment>);
    }
}

export class VideoAsset {
    "id": string;
    "cloudAssetId": string;
    "name": string;
    "durationMs": number;
    "sourceUrl"?: string;

    /** Creates a new VideoAsset instance. */
    constructor($$source: Partial<VideoAsset> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cloudAssetId" in $$source)) {
            this["cloudAssetId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoAsset($$parsedSource as Partial<VideoAsset>);
    }
}

// Private type creation functions
const $$createType0 = VideoAsset.createFrom;
const $$createType1 = Scene.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = TranscriptSegment.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = HighlightCandidate.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = EditSuggestion.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
