// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CameraService is the Wails-facing camera facade. It deliberately contains
 * no cloud, library, or editing dependencies so the camera binary stays local.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as camera$0 from "../camera/models.js";

export function Discover(): $CancellablePromise<camera$0.CameraDevice[]> {
    return $Call.ByID(4230413248).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetConnectionStatus(): $CancellablePromise<camera$0.ConnectionStatus> {
    return $Call.ByID(2633529107).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListMedia($0: string): $CancellablePromise<camera$0.CameraMediaItem[]> {
    return $Call.ByID(3971924957, $0).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ProbeEndpoint(req: camera$0.EndpointProbeRequest): $CancellablePromise<camera$0.EndpointProbeResult> {
    return $Call.ByID(1095969850, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ProbeEndpointCandidates(req: camera$0.EndpointProbeRequest): $CancellablePromise<camera$0.EndpointProbePlan> {
    return $Call.ByID(1993486232, req).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ValidationChecklist(): $CancellablePromise<camera$0.ValidationStep[]> {
    return $Call.ByID(960251172).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = camera$0.CameraDevice.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = camera$0.ConnectionStatus.createFrom;
const $$createType3 = camera$0.CameraMediaItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = camera$0.EndpointProbeResult.createFrom;
const $$createType6 = camera$0.EndpointProbePlan.createFrom;
const $$createType7 = camera$0.ValidationStep.createFrom;
const $$createType8 = $Create.Array($$createType7);
