// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dji$0 from "../dji/models.js";

export function Pair(req: dji$0.PairingRequest): $CancellablePromise<dji$0.PairingResult> {
    return $Call.ByID(2811849074, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ProtocolProfile(): $CancellablePromise<dji$0.ProtocolProfile> {
    return $Call.ByID(4116901535).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RunDiagnostics(id: string): $CancellablePromise<dji$0.DiagnosticResult> {
    return $Call.ByID(368443593, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ScanBLE(): $CancellablePromise<dji$0.BLEDevice[]> {
    return $Call.ByID(1508376708).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetupWiFi(req: dji$0.WiFiSetupRequest): $CancellablePromise<dji$0.WiFiProfile> {
    return $Call.ByID(367178610, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Status(): $CancellablePromise<dji$0.ControlStatus> {
    return $Call.ByID(1140700876).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = dji$0.PairingResult.createFrom;
const $$createType1 = dji$0.ProtocolProfile.createFrom;
const $$createType2 = dji$0.DiagnosticResult.createFrom;
const $$createType3 = dji$0.BLEDevice.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = dji$0.WiFiProfile.createFrom;
const $$createType6 = dji$0.ControlStatus.createFrom;
