// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CameraDevice {
    "id": string;
    "name": string;
    "model": string;
    "ipAddress": string;
    "batteryLevel"?: number;
    "connected": boolean;
    "lastSeen"?: string;

    /** Creates a new CameraDevice instance. */
    constructor($$source: Partial<CameraDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("ipAddress" in $$source)) {
            this["ipAddress"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CameraDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): CameraDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CameraDevice($$parsedSource as Partial<CameraDevice>);
    }
}

export class CameraMediaItem {
    "id": string;
    "name": string;
    "path": string;
    "storage": CameraStorage;
    "sizeBytes": number;
    "contentType": string;
    "capturedAt"?: string;
    "durationMs"?: number;
    "rangeOk": boolean;
    "endpointUrl"?: string;

    /** Creates a new CameraMediaItem instance. */
    constructor($$source: Partial<CameraMediaItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("storage" in $$source)) {
            this["storage"] = CameraStorage.$zero;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }
        if (!("rangeOk" in $$source)) {
            this["rangeOk"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CameraMediaItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CameraMediaItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CameraMediaItem($$parsedSource as Partial<CameraMediaItem>);
    }
}

export enum CameraStorage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CameraStorageInternal = "internal",
    CameraStorageSD = "sd",
};

export class ConnectionStatus {
    "available": boolean;
    "message": string;

    /** Creates a new ConnectionStatus instance. */
    constructor($$source: Partial<ConnectionStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus($$parsedSource as Partial<ConnectionStatus>);
    }
}

export class EndpointProbePlan {
    "ipAddress": string;
    "path": string;
    "storage": CameraStorage;
    "ports": number[];
    "results": EndpointProbeResult[];
    "message": string;

    /** Creates a new EndpointProbePlan instance. */
    constructor($$source: Partial<EndpointProbePlan> = {}) {
        if (!("ipAddress" in $$source)) {
            this["ipAddress"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("storage" in $$source)) {
            this["storage"] = CameraStorage.$zero;
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointProbePlan instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointProbePlan {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField3_0($$parsedSource["ports"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField4_0($$parsedSource["results"]);
        }
        return new EndpointProbePlan($$parsedSource as Partial<EndpointProbePlan>);
    }
}

export class EndpointProbeRequest {
    "deviceId"?: string;
    "ipAddress"?: string;
    "port"?: number;
    "path"?: string;
    "storage"?: CameraStorage;

    /** Creates a new EndpointProbeRequest instance. */
    constructor($$source: Partial<EndpointProbeRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointProbeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointProbeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointProbeRequest($$parsedSource as Partial<EndpointProbeRequest>);
    }
}

export class EndpointProbeResult {
    "baseUrl": string;
    "endpointPath": string;
    "reachable": boolean;
    "v2EndpointOk": boolean;
    "headOk": boolean;
    "rangeOk": boolean;
    "contentLength"?: number;
    "contentType"?: string;
    "statusCode"?: number;
    "message": string;
    "checkedAt": string;

    /** Creates a new EndpointProbeResult instance. */
    constructor($$source: Partial<EndpointProbeResult> = {}) {
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("endpointPath" in $$source)) {
            this["endpointPath"] = "";
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("v2EndpointOk" in $$source)) {
            this["v2EndpointOk"] = false;
        }
        if (!("headOk" in $$source)) {
            this["headOk"] = false;
        }
        if (!("rangeOk" in $$source)) {
            this["rangeOk"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("checkedAt" in $$source)) {
            this["checkedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EndpointProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EndpointProbeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EndpointProbeResult($$parsedSource as Partial<EndpointProbeResult>);
    }
}

export class ValidationStep {
    "id": string;
    "label": string;
    "status": string;
    "description": string;

    /** Creates a new ValidationStep instance. */
    constructor($$source: Partial<ValidationStep> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationStep instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationStep($$parsedSource as Partial<ValidationStep>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = EndpointProbeResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
