// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BindingEvaluation {
    "name": string;
    "package": string;
    "license": string;
    "integrationMode": string;
    "decision": string;
    "strengths": string[];
    "risks": string[];

    /** Creates a new BindingEvaluation instance. */
    constructor($$source: Partial<BindingEvaluation> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("package" in $$source)) {
            this["package"] = "";
        }
        if (!("license" in $$source)) {
            this["license"] = "";
        }
        if (!("integrationMode" in $$source)) {
            this["integrationMode"] = "";
        }
        if (!("decision" in $$source)) {
            this["decision"] = "";
        }
        if (!("strengths" in $$source)) {
            this["strengths"] = [];
        }
        if (!("risks" in $$source)) {
            this["risks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BindingEvaluation instance from a string or object.
     */
    static createFrom($$source: any = {}): BindingEvaluation {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("strengths" in $$parsedSource) {
            $$parsedSource["strengths"] = $$createField5_0($$parsedSource["strengths"]);
        }
        if ("risks" in $$parsedSource) {
            $$parsedSource["risks"] = $$createField6_0($$parsedSource["risks"]);
        }
        return new BindingEvaluation($$parsedSource as Partial<BindingEvaluation>);
    }
}

export class ProbeResult {
    "path": string;
    "durationMs": number;
    "width": number;
    "height": number;
    "frameRate": number;
    "videoCodec": string;
    "audioCodec": string;

    /** Creates a new ProbeResult instance. */
    constructor($$source: Partial<ProbeResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("frameRate" in $$source)) {
            this["frameRate"] = 0;
        }
        if (!("videoCodec" in $$source)) {
            this["videoCodec"] = "";
        }
        if (!("audioCodec" in $$source)) {
            this["audioCodec"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeResult($$parsedSource as Partial<ProbeResult>);
    }
}

export class RenderClip {
    "id": string;
    "input": string;
    "inMs": number;
    "outMs": number;
    "muted"?: boolean;

    /** Creates a new RenderClip instance. */
    constructor($$source: Partial<RenderClip> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("inMs" in $$source)) {
            this["inMs"] = 0;
        }
        if (!("outMs" in $$source)) {
            this["outMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderClip instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderClip {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderClip($$parsedSource as Partial<RenderClip>);
    }
}

export class RenderJob {
    "id": string;
    "projectId": string;
    "status": string;
    "output"?: string;
    "message"?: string;
    "log"?: string;

    /** Creates a new RenderJob instance. */
    constructor($$source: Partial<RenderJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderJob instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderJob($$parsedSource as Partial<RenderJob>);
    }
}

export class RenderRequest {
    "projectId": string;
    "presetId": string;
    "output": string;
    "clips": RenderClip[];
    "textOverlays"?: RenderTextOverlay[];
    "width"?: number;
    "height"?: number;
    "videoCodec"?: string;
    "audioCodec"?: string;

    /** Creates a new RenderRequest instance. */
    constructor($$source: Partial<RenderRequest> = {}) {
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("presetId" in $$source)) {
            this["presetId"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("clips" in $$source)) {
            this["clips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderRequest {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField3_0($$parsedSource["clips"]);
        }
        if ("textOverlays" in $$parsedSource) {
            $$parsedSource["textOverlays"] = $$createField4_0($$parsedSource["textOverlays"]);
        }
        return new RenderRequest($$parsedSource as Partial<RenderRequest>);
    }
}

export class RenderTextOverlay {
    "id": string;
    "text": string;
    "startMs": number;
    "endMs": number;

    /** Creates a new RenderTextOverlay instance. */
    constructor($$source: Partial<RenderTextOverlay> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderTextOverlay instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderTextOverlay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderTextOverlay($$parsedSource as Partial<RenderTextOverlay>);
    }
}

export class RuntimeStatus {
    "available": boolean;
    "backend": string;
    "ffmpegPath"?: string;
    "ffmpegVersion"?: string;
    "ffprobePath"?: string;
    "ffprobeVersion"?: string;
    "message": string;

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("backend" in $$source)) {
            this["backend"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}

export class ThumbnailRequest {
    "assetId": string;
    "input": string;
    "output": string;
    "timeMs": number;
    "width": number;

    /** Creates a new ThumbnailRequest instance. */
    constructor($$source: Partial<ThumbnailRequest> = {}) {
        if (!("assetId" in $$source)) {
            this["assetId"] = "";
        }
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("timeMs" in $$source)) {
            this["timeMs"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThumbnailRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ThumbnailRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThumbnailRequest($$parsedSource as Partial<ThumbnailRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = RenderClip.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = RenderTextOverlay.createFrom;
const $$createType4 = $Create.Array($$createType3);
