// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class CompositionClip {
    "id": string;
    "sourceAssetId": string;
    "suggestionId": string;
    "title": string;
    "reason": string;
    "startMs": number;
    "endMs": number;
    "score": number;
    "sourceRefs": SourceRef[];

    /** Creates a new CompositionClip instance. */
    constructor($$source: Partial<CompositionClip> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sourceAssetId" in $$source)) {
            this["sourceAssetId"] = "";
        }
        if (!("suggestionId" in $$source)) {
            this["suggestionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("sourceRefs" in $$source)) {
            this["sourceRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositionClip instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositionClip {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField8_0($$parsedSource["sourceRefs"]);
        }
        return new CompositionClip($$parsedSource as Partial<CompositionClip>);
    }
}

/**
 * CompositionEditPlan is the grounded, ordered recommendation for a Smart Edit
 * composition. It is deliberately separate from EditPlan so single-video
 * planner responses remain backwards compatible.
 */
export class CompositionEditPlan {
    "schemaVersion": number;
    "compositionId": string;
    "narrativeIntent"?: string;
    "pacingProfile"?: NarrativePacingProfile;
    "variantCount"?: number;
    "pacingClassifierMode"?: NarrativePacingClassifierMode;
    "pacingFallbackReason"?: NarrativePacingClassifierFallbackReason;
    "editorialProfile"?: NarrativeIntentProfile;
    "planningMode"?: NarrativeSegmentPlanningMode;
    "planningFallbackReason"?: NarrativeSegmentPlanningFallbackReason;
    "title": string;
    "summary": string;
    "rankingMode": string;
    "recommendationVersion": string;
    "evidenceFingerprint": string;
    "sourceAssetIds": string[];
    "sources": CompositionSourceStatus[];
    "clips": CompositionClip[];
    "sourceRefs": SourceRef[];

    /** Creates a new CompositionEditPlan instance. */
    constructor($$source: Partial<CompositionEditPlan> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("compositionId" in $$source)) {
            this["compositionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("rankingMode" in $$source)) {
            this["rankingMode"] = "";
        }
        if (!("recommendationVersion" in $$source)) {
            this["recommendationVersion"] = "";
        }
        if (!("evidenceFingerprint" in $$source)) {
            this["evidenceFingerprint"] = "";
        }
        if (!("sourceAssetIds" in $$source)) {
            this["sourceAssetIds"] = [];
        }
        if (!("sources" in $$source)) {
            this["sources"] = [];
        }
        if (!("clips" in $$source)) {
            this["clips"] = [];
        }
        if (!("sourceRefs" in $$source)) {
            this["sourceRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositionEditPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositionEditPlan {
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType4;
        const $$createField17_0 = $$createType6;
        const $$createField18_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceAssetIds" in $$parsedSource) {
            $$parsedSource["sourceAssetIds"] = $$createField15_0($$parsedSource["sourceAssetIds"]);
        }
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField16_0($$parsedSource["sources"]);
        }
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField17_0($$parsedSource["clips"]);
        }
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField18_0($$parsedSource["sourceRefs"]);
        }
        return new CompositionEditPlan($$parsedSource as Partial<CompositionEditPlan>);
    }
}

export class CompositionSourceStatus {
    "assetId": string;
    "analysisJobId": string;
    "status": string;
    "durationMs": number;

    /** Creates a new CompositionSourceStatus instance. */
    constructor($$source: Partial<CompositionSourceStatus> = {}) {
        if (!("assetId" in $$source)) {
            this["assetId"] = "";
        }
        if (!("analysisJobId" in $$source)) {
            this["analysisJobId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompositionSourceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CompositionSourceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompositionSourceStatus($$parsedSource as Partial<CompositionSourceStatus>);
    }
}

export class EditPlan {
    "schemaVersion": number;
    "videoId": string;
    "assetId": string;
    "sourceAssetIds"?: string[];
    "title": string;
    "summary": string;
    "highlights"?: Highlight[];
    "suggestions"?: EditSuggestion[];
    "sourceRefs"?: SourceRef[];

    /** Creates a new EditPlan instance. */
    constructor($$source: Partial<EditPlan> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("videoId" in $$source)) {
            this["videoId"] = "";
        }
        if (!("assetId" in $$source)) {
            this["assetId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): EditPlan {
        const $$createField3_0 = $$createType2;
        const $$createField6_0 = $$createType8;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceAssetIds" in $$parsedSource) {
            $$parsedSource["sourceAssetIds"] = $$createField3_0($$parsedSource["sourceAssetIds"]);
        }
        if ("highlights" in $$parsedSource) {
            $$parsedSource["highlights"] = $$createField6_0($$parsedSource["highlights"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField7_0($$parsedSource["suggestions"]);
        }
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField8_0($$parsedSource["sourceRefs"]);
        }
        return new EditPlan($$parsedSource as Partial<EditPlan>);
    }
}

export class EditSuggestion {
    "id": string;
    "title": string;
    "reason": string;
    "startMs": number;
    "endMs": number;
    "score": number;
    "sourceRefs": SourceRef[];
    "clips"?: SuggestedClip[];

    /** Creates a new EditSuggestion instance. */
    constructor($$source: Partial<EditSuggestion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("sourceRefs" in $$source)) {
            this["sourceRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): EditSuggestion {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField6_0($$parsedSource["sourceRefs"]);
        }
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField7_0($$parsedSource["clips"]);
        }
        return new EditSuggestion($$parsedSource as Partial<EditSuggestion>);
    }
}

export class Highlight {
    "id": string;
    "title": string;
    "reason": string;
    "startMs": number;
    "endMs": number;
    "score": number;
    "sourceRefs": SourceRef[];

    /** Creates a new Highlight instance. */
    constructor($$source: Partial<Highlight> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("sourceRefs" in $$source)) {
            this["sourceRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Highlight instance from a string or object.
     */
    static createFrom($$source: any = {}): Highlight {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField6_0($$parsedSource["sourceRefs"]);
        }
        return new Highlight($$parsedSource as Partial<Highlight>);
    }
}

export class JobCheckpoint {
    "stage": string;
    "at": string;
    "videoId"?: string;
    "state"?: string;
    "detail"?: string;
    "metadata"?: json$0.RawMessage;

    /** Creates a new JobCheckpoint instance. */
    constructor($$source: Partial<JobCheckpoint> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobCheckpoint instance from a string or object.
     */
    static createFrom($$source: any = {}): JobCheckpoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobCheckpoint($$parsedSource as Partial<JobCheckpoint>);
    }
}

export class MediaAudioSignals {
    "present": boolean;
    "codec"?: string;
    "channels"?: number;
    "sampleRate"?: number;

    /** Creates a new MediaAudioSignals instance. */
    constructor($$source: Partial<MediaAudioSignals> = {}) {
        if (!("present" in $$source)) {
            this["present"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaAudioSignals instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaAudioSignals {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaAudioSignals($$parsedSource as Partial<MediaAudioSignals>);
    }
}

export class MediaSignals {
    "sourceUrl": string;
    "duration": time$0.Duration;
    "video": MediaVideoSignals;
    "audio": MediaAudioSignals;
    "silences"?: SilenceInterval[];

    /** Creates a new MediaSignals instance. */
    constructor($$source: Partial<MediaSignals> = {}) {
        if (!("sourceUrl" in $$source)) {
            this["sourceUrl"] = "";
        }
        if (!("duration" in $$source)) {
            this["duration"] = time$0.Duration.$zero;
        }
        if (!("video" in $$source)) {
            this["video"] = (new MediaVideoSignals());
        }
        if (!("audio" in $$source)) {
            this["audio"] = (new MediaAudioSignals());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaSignals instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaSignals {
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType14;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("video" in $$parsedSource) {
            $$parsedSource["video"] = $$createField2_0($$parsedSource["video"]);
        }
        if ("audio" in $$parsedSource) {
            $$parsedSource["audio"] = $$createField3_0($$parsedSource["audio"]);
        }
        if ("silences" in $$parsedSource) {
            $$parsedSource["silences"] = $$createField4_0($$parsedSource["silences"]);
        }
        return new MediaSignals($$parsedSource as Partial<MediaSignals>);
    }
}

export class MediaVideoSignals {
    "present": boolean;
    "codec"?: string;
    "width"?: number;
    "height"?: number;
    "fps"?: number;

    /** Creates a new MediaVideoSignals instance. */
    constructor($$source: Partial<MediaVideoSignals> = {}) {
        if (!("present" in $$source)) {
            this["present"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaVideoSignals instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaVideoSignals {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaVideoSignals($$parsedSource as Partial<MediaVideoSignals>);
    }
}

/**
 * NarrativeIntentProfile is the closed result contract returned by the
 * classifier. It is mapped locally to a pacing profile before any candidates
 * are selected.
 */
export enum NarrativeIntentProfile {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativeIntentProfileStandard = "standard",
    NarrativeIntentProfileEnergetic = "energetic",
    NarrativeIntentProfileCalm = "calm",
    NarrativeIntentProfileChronological = "chronological",
    NarrativeIntentProfileCinematic = "cinematic",
    NarrativeIntentProfileSocialShortForm = "social_short_form",
    NarrativeIntentProfileTutorial = "tutorial",
    NarrativeIntentProfileHighlightReel = "highlight_reel",
    NarrativeIntentProfileRecap = "recap",
    NarrativeIntentProfileStorytelling = "storytelling",
    NarrativeIntentProfileTravel = "travel",
    NarrativeIntentProfileInterview = "interview",
    NarrativeIntentProfileProductShowcase = "product_showcase",
};

export enum NarrativePacingClassifierFallbackReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativePacingClassifierFallbackNone = "",
    NarrativePacingClassifierFallbackNoIntent = "no_intent",
    NarrativePacingClassifierFallbackUnavailable = "classifier_unavailable",
    NarrativePacingClassifierFallbackTimeout = "classifier_timeout",
    NarrativePacingClassifierFallbackInvalidResponse = "classifier_invalid_response",
    NarrativePacingClassifierFallbackRequestFailed = "classifier_request_failed",
};

export enum NarrativePacingClassifierMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativePacingClassifierModeFoundryStructured = "foundry_structured",
    NarrativePacingClassifierModeDeterministicKeywordFallback = "deterministic_keyword_fallback",
    NarrativePacingClassifierModeStandardFallback = "standard_fallback",
};

export enum NarrativePacingProfile {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativePacingProfileStandard = "standard",
    NarrativePacingProfileEnergeticShortForm = "energetic_short_form",
    NarrativePacingProfileCalmRecap = "calm_recap",
    NarrativePacingProfileChronologicalContinuity = "chronological_continuity",
    NarrativePacingProfileCinematic = "cinematic",
    NarrativePacingProfileSocialShortForm = "social_short_form",
    NarrativePacingProfileTutorial = "tutorial",
    NarrativePacingProfileHighlightReel = "highlight_reel",
    NarrativePacingProfileRecap = "recap",
    NarrativePacingProfileStorytelling = "storytelling",
    NarrativePacingProfileTravel = "travel",
    NarrativePacingProfileInterview = "interview",
    NarrativePacingProfileProductShowcase = "product_showcase",
};

export enum NarrativeSegmentPlanningFallbackReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativeSegmentPlanningFallbackNone = "",
    NarrativeSegmentPlanningFallbackUnavailable = "planner_unavailable",
    NarrativeSegmentPlanningFallbackTimeout = "planner_timeout",
    NarrativeSegmentPlanningFallbackInvalidResponse = "planner_invalid_response",
    NarrativeSegmentPlanningFallbackRequestFailed = "planner_request_failed",
    NarrativeSegmentPlanningFallbackCatalogInvalid = "planner_catalog_invalid",
};

export enum NarrativeSegmentPlanningMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NarrativeSegmentPlanningModeFoundryStructured = "foundry_structured",
    NarrativeSegmentPlanningModeDeterministic = "deterministic_local",
};

export class SilenceInterval {
    "start": time$0.Duration;
    "end": time$0.Duration;

    /** Creates a new SilenceInterval instance. */
    constructor($$source: Partial<SilenceInterval> = {}) {
        if (!("start" in $$source)) {
            this["start"] = time$0.Duration.$zero;
        }
        if (!("end" in $$source)) {
            this["end"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SilenceInterval instance from a string or object.
     */
    static createFrom($$source: any = {}): SilenceInterval {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SilenceInterval($$parsedSource as Partial<SilenceInterval>);
    }
}

export class SourceRef {
    "refId": string;
    "sourceKind": string;
    "sourceAssetId": string;
    "factKind"?: string;
    "startMs"?: number;
    "endMs"?: number;
    "text"?: string;

    /** Creates a new SourceRef instance. */
    constructor($$source: Partial<SourceRef> = {}) {
        if (!("refId" in $$source)) {
            this["refId"] = "";
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("sourceAssetId" in $$source)) {
            this["sourceAssetId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceRef instance from a string or object.
     */
    static createFrom($$source: any = {}): SourceRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceRef($$parsedSource as Partial<SourceRef>);
    }
}

export class SuggestedClip {
    "id": string;
    "title": string;
    "reason": string;
    "sourceAssetId"?: string;
    "startMs": number;
    "endMs": number;
    "score": number;
    "sourceRefs": SourceRef[];

    /** Creates a new SuggestedClip instance. */
    constructor($$source: Partial<SuggestedClip> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("sourceRefs" in $$source)) {
            this["sourceRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuggestedClip instance from a string or object.
     */
    static createFrom($$source: any = {}): SuggestedClip {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceRefs" in $$parsedSource) {
            $$parsedSource["sourceRefs"] = $$createField7_0($$parsedSource["sourceRefs"]);
        }
        return new SuggestedClip($$parsedSource as Partial<SuggestedClip>);
    }
}

export class ThumbnailRef {
    "videoId"?: string;
    "thumbnailId"?: string;
    "url"?: string;

    /** Creates a new ThumbnailRef instance. */
    constructor($$source: Partial<ThumbnailRef> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThumbnailRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ThumbnailRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThumbnailRef($$parsedSource as Partial<ThumbnailRef>);
    }
}

export class TimelineClip {
    "id": string;
    "sourceAssetId": string;
    "inMs": number;
    "outMs": number;
    "timelineStartMs": number;
    "durationMs": number;
    "transition": TimelineTransition;

    /** Creates a new TimelineClip instance. */
    constructor($$source: Partial<TimelineClip> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sourceAssetId" in $$source)) {
            this["sourceAssetId"] = "";
        }
        if (!("inMs" in $$source)) {
            this["inMs"] = 0;
        }
        if (!("outMs" in $$source)) {
            this["outMs"] = 0;
        }
        if (!("timelineStartMs" in $$source)) {
            this["timelineStartMs"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("transition" in $$source)) {
            this["transition"] = (new TimelineTransition());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineClip instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineClip {
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transition" in $$parsedSource) {
            $$parsedSource["transition"] = $$createField6_0($$parsedSource["transition"]);
        }
        return new TimelineClip($$parsedSource as Partial<TimelineClip>);
    }
}

export class TimelineDraft {
    "schemaVersion": number;
    "originJobId": string;
    "suggestionId": string;
    "promptVersion": string;
    "primaryVideoTrack": TimelineTrack;

    /** Creates a new TimelineDraft instance. */
    constructor($$source: Partial<TimelineDraft> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("originJobId" in $$source)) {
            this["originJobId"] = "";
        }
        if (!("suggestionId" in $$source)) {
            this["suggestionId"] = "";
        }
        if (!("promptVersion" in $$source)) {
            this["promptVersion"] = "";
        }
        if (!("primaryVideoTrack" in $$source)) {
            this["primaryVideoTrack"] = (new TimelineTrack());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineDraft instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineDraft {
        const $$createField4_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primaryVideoTrack" in $$parsedSource) {
            $$parsedSource["primaryVideoTrack"] = $$createField4_0($$parsedSource["primaryVideoTrack"]);
        }
        return new TimelineDraft($$parsedSource as Partial<TimelineDraft>);
    }
}

export class TimelineTrack {
    "id": string;
    "kind": string;
    "clips": TimelineClip[];

    /** Creates a new TimelineTrack instance. */
    constructor($$source: Partial<TimelineTrack> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("clips" in $$source)) {
            this["clips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineTrack {
        const $$createField2_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField2_0($$parsedSource["clips"]);
        }
        return new TimelineTrack($$parsedSource as Partial<TimelineTrack>);
    }
}

export class TimelineTransition {
    "kind": string;
    "durationMs"?: number;

    /** Creates a new TimelineTransition instance. */
    constructor($$source: Partial<TimelineTransition> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimelineTransition instance from a string or object.
     */
    static createFrom($$source: any = {}): TimelineTransition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimelineTransition($$parsedSource as Partial<TimelineTransition>);
    }
}

export class VideoIndexInsights {
    "speakers"?: VideoIndexSpeaker[];
    "scenes"?: VideoIndexScene[];
    "shots"?: VideoIndexShot[];
    "keyframes"?: VideoIndexKeyframe[];
    "transcript"?: VideoIndexTranscript[];
    "ocr"?: VideoIndexOCR[];
    "labels"?: VideoIndexLabel[];
    "objects"?: VideoIndexObject[];

    /** Creates a new VideoIndexInsights instance. */
    constructor($$source: Partial<VideoIndexInsights> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexInsights instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexInsights {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType24;
        const $$createField2_0 = $$createType26;
        const $$createField3_0 = $$createType28;
        const $$createField4_0 = $$createType30;
        const $$createField5_0 = $$createType32;
        const $$createField6_0 = $$createType34;
        const $$createField7_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("speakers" in $$parsedSource) {
            $$parsedSource["speakers"] = $$createField0_0($$parsedSource["speakers"]);
        }
        if ("scenes" in $$parsedSource) {
            $$parsedSource["scenes"] = $$createField1_0($$parsedSource["scenes"]);
        }
        if ("shots" in $$parsedSource) {
            $$parsedSource["shots"] = $$createField2_0($$parsedSource["shots"]);
        }
        if ("keyframes" in $$parsedSource) {
            $$parsedSource["keyframes"] = $$createField3_0($$parsedSource["keyframes"]);
        }
        if ("transcript" in $$parsedSource) {
            $$parsedSource["transcript"] = $$createField4_0($$parsedSource["transcript"]);
        }
        if ("ocr" in $$parsedSource) {
            $$parsedSource["ocr"] = $$createField5_0($$parsedSource["ocr"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField6_0($$parsedSource["labels"]);
        }
        if ("objects" in $$parsedSource) {
            $$parsedSource["objects"] = $$createField7_0($$parsedSource["objects"]);
        }
        return new VideoIndexInsights($$parsedSource as Partial<VideoIndexInsights>);
    }
}

export class VideoIndexKeyframe {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "shotId"?: string;
    "startMs": number;
    "endMs": number;
    "confidence"?: number;
    "thumbnail": ThumbnailRef;

    /** Creates a new VideoIndexKeyframe instance. */
    constructor($$source: Partial<VideoIndexKeyframe> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("thumbnail" in $$source)) {
            this["thumbnail"] = (new ThumbnailRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexKeyframe instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexKeyframe {
        const $$createField7_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("thumbnail" in $$parsedSource) {
            $$parsedSource["thumbnail"] = $$createField7_0($$parsedSource["thumbnail"]);
        }
        return new VideoIndexKeyframe($$parsedSource as Partial<VideoIndexKeyframe>);
    }
}

export class VideoIndexLabel {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "language"?: string;
    "name": string;
    "referenceId"?: string;
    "startMs": number;
    "endMs": number;
    "confidence"?: number;

    /** Creates a new VideoIndexLabel instance. */
    constructor($$source: Partial<VideoIndexLabel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexLabel instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexLabel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoIndexLabel($$parsedSource as Partial<VideoIndexLabel>);
    }
}

export class VideoIndexOCR {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "language"?: string;
    "text": string;
    "startMs": number;
    "endMs": number;
    "confidence"?: number;
    "bounds"?: VideoIndexRect;

    /** Creates a new VideoIndexOCR instance. */
    constructor($$source: Partial<VideoIndexOCR> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexOCR instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexOCR {
        const $$createField8_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bounds" in $$parsedSource) {
            $$parsedSource["bounds"] = $$createField8_0($$parsedSource["bounds"]);
        }
        return new VideoIndexOCR($$parsedSource as Partial<VideoIndexOCR>);
    }
}

export class VideoIndexObject {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "type": string;
    "displayName"?: string;
    "wikiDataId"?: string;
    "startMs": number;
    "endMs": number;
    "confidence"?: number;
    "thumbnail"?: ThumbnailRef;

    /** Creates a new VideoIndexObject instance. */
    constructor($$source: Partial<VideoIndexObject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexObject instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexObject {
        const $$createField9_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("thumbnail" in $$parsedSource) {
            $$parsedSource["thumbnail"] = $$createField9_0($$parsedSource["thumbnail"]);
        }
        return new VideoIndexObject($$parsedSource as Partial<VideoIndexObject>);
    }
}

export class VideoIndexRect {
    "left"?: number;
    "top"?: number;
    "width"?: number;
    "height"?: number;
    "angle"?: number;

    /** Creates a new VideoIndexRect instance. */
    constructor($$source: Partial<VideoIndexRect> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexRect instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexRect {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoIndexRect($$parsedSource as Partial<VideoIndexRect>);
    }
}

export class VideoIndexResult {
    "videoId": string;
    "state"?: string;
    "durationMs"?: number;
    "detectedLanguage"?: string;
    "sourceLanguage"?: string;
    "sourceLanguages"?: string[];
    "sourceIds"?: string[];
    "videos"?: VideoIndexVideo[];
    "insights": VideoIndexInsights;
    "technicalSignals"?: MediaSignals | null;

    /** Creates a new VideoIndexResult instance. */
    constructor($$source: Partial<VideoIndexResult> = {}) {
        if (!("videoId" in $$source)) {
            this["videoId"] = "";
        }
        if (!("insights" in $$source)) {
            this["insights"] = (new VideoIndexInsights());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexResult {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType40;
        const $$createField8_0 = $$createType41;
        const $$createField9_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceLanguages" in $$parsedSource) {
            $$parsedSource["sourceLanguages"] = $$createField5_0($$parsedSource["sourceLanguages"]);
        }
        if ("sourceIds" in $$parsedSource) {
            $$parsedSource["sourceIds"] = $$createField6_0($$parsedSource["sourceIds"]);
        }
        if ("videos" in $$parsedSource) {
            $$parsedSource["videos"] = $$createField7_0($$parsedSource["videos"]);
        }
        if ("insights" in $$parsedSource) {
            $$parsedSource["insights"] = $$createField8_0($$parsedSource["insights"]);
        }
        if ("technicalSignals" in $$parsedSource) {
            $$parsedSource["technicalSignals"] = $$createField9_0($$parsedSource["technicalSignals"]);
        }
        return new VideoIndexResult($$parsedSource as Partial<VideoIndexResult>);
    }
}

export class VideoIndexScene {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "startMs": number;
    "endMs": number;
    "confidence"?: number;
    "thumbnail"?: ThumbnailRef | null;

    /** Creates a new VideoIndexScene instance. */
    constructor($$source: Partial<VideoIndexScene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexScene instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexScene {
        const $$createField6_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("thumbnail" in $$parsedSource) {
            $$parsedSource["thumbnail"] = $$createField6_0($$parsedSource["thumbnail"]);
        }
        return new VideoIndexScene($$parsedSource as Partial<VideoIndexScene>);
    }
}

export class VideoIndexShot {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "startMs": number;
    "endMs": number;
    "tags"?: string[];
    "keyframeIds"?: string[];
    "confidence"?: number;

    /** Creates a new VideoIndexShot instance. */
    constructor($$source: Partial<VideoIndexShot> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexShot instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexShot {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        if ("keyframeIds" in $$parsedSource) {
            $$parsedSource["keyframeIds"] = $$createField6_0($$parsedSource["keyframeIds"]);
        }
        return new VideoIndexShot($$parsedSource as Partial<VideoIndexShot>);
    }
}

export class VideoIndexSpeaker {
    "id": string;
    "name"?: string;
    "language"?: string;
    "transcriptIds"?: string[];

    /** Creates a new VideoIndexSpeaker instance. */
    constructor($$source: Partial<VideoIndexSpeaker> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexSpeaker instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexSpeaker {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transcriptIds" in $$parsedSource) {
            $$parsedSource["transcriptIds"] = $$createField3_0($$parsedSource["transcriptIds"]);
        }
        return new VideoIndexSpeaker($$parsedSource as Partial<VideoIndexSpeaker>);
    }
}

export class VideoIndexTranscript {
    "id": string;
    "indexId"?: number;
    "sourceId"?: string;
    "speakerId"?: string;
    "speakerName"?: string;
    "language"?: string;
    "startMs": number;
    "endMs": number;
    "text": string;
    "confidence"?: number;

    /** Creates a new VideoIndexTranscript instance. */
    constructor($$source: Partial<VideoIndexTranscript> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexTranscript instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexTranscript {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoIndexTranscript($$parsedSource as Partial<VideoIndexTranscript>);
    }
}

export class VideoIndexVideo {
    "id": string;
    "sourceId"?: string;
    "durationMs"?: number;
    "detectedLanguage"?: string;
    "confidence"?: number;

    /** Creates a new VideoIndexVideo instance. */
    constructor($$source: Partial<VideoIndexVideo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VideoIndexVideo instance from a string or object.
     */
    static createFrom($$source: any = {}): VideoIndexVideo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VideoIndexVideo($$parsedSource as Partial<VideoIndexVideo>);
    }
}

// Private type creation functions
const $$createType0 = SourceRef.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = CompositionSourceStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CompositionClip.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Highlight.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = EditSuggestion.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = SuggestedClip.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = MediaVideoSignals.createFrom;
const $$createType14 = MediaAudioSignals.createFrom;
const $$createType15 = SilenceInterval.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = TimelineTransition.createFrom;
const $$createType18 = TimelineTrack.createFrom;
const $$createType19 = TimelineClip.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = VideoIndexSpeaker.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = VideoIndexScene.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = VideoIndexShot.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = VideoIndexKeyframe.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = VideoIndexTranscript.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = VideoIndexOCR.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = VideoIndexLabel.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = VideoIndexObject.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = ThumbnailRef.createFrom;
const $$createType38 = VideoIndexRect.createFrom;
const $$createType39 = VideoIndexVideo.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = VideoIndexInsights.createFrom;
const $$createType42 = MediaSignals.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = $Create.Nullable($$createType37);
