// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Duration represents the elapsed time between two instants
 * as an int64 nanosecond count. The representation limits the
 * largest representable duration to approximately 290 years.
 */
export enum Duration {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    minDuration = -9223372036854775808,
    maxDuration = 9223372036854775807,

    /**
     * Common durations. There is no definition for units of Day or larger
     * to avoid confusion across daylight savings time zone transitions.
     * 
     * To count the number of units in a [Duration], divide:
     * 
     * 	second := time.Second
     * 	fmt.Print(int64(second/time.Millisecond)) // prints 1000
     * 
     * To convert an integer number of units to a Duration, multiply:
     * 
     * 	seconds := 10
     * 	fmt.Print(time.Duration(seconds)*time.Second) // prints 10s
     */
    Nanosecond = 1,
    Microsecond = 1000,
    Millisecond = 1000000,
    Second = 1000000000,
    Minute = 60000000000,
    Hour = 3600000000000,
};
