// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ClipSegment {
    "id": string;
    "sourceAssetId": string;
    "inMs": number;
    "outMs": number;
    "timelineStartMs"?: number;
    "durationMs"?: number;
    "transition"?: Transition | null;

    /** Creates a new ClipSegment instance. */
    constructor($$source: Partial<ClipSegment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sourceAssetId" in $$source)) {
            this["sourceAssetId"] = "";
        }
        if (!("inMs" in $$source)) {
            this["inMs"] = 0;
        }
        if (!("outMs" in $$source)) {
            this["outMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipSegment instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipSegment {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("transition" in $$parsedSource) {
            $$parsedSource["transition"] = $$createField6_0($$parsedSource["transition"]);
        }
        return new ClipSegment($$parsedSource as Partial<ClipSegment>);
    }
}

export class EditProject {
    "id": string;
    "name": string;
    "assetIds": string[];
    "timeline": Timeline;
    "renderPreset"?: string;
    "originJobId"?: string;
    "suggestionId"?: string;
    "promptVersion"?: string;

    /** Creates a new EditProject instance. */
    constructor($$source: Partial<EditProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("assetIds" in $$source)) {
            this["assetIds"] = [];
        }
        if (!("timeline" in $$source)) {
            this["timeline"] = (new Timeline());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditProject instance from a string or object.
     */
    static createFrom($$source: any = {}): EditProject {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assetIds" in $$parsedSource) {
            $$parsedSource["assetIds"] = $$createField2_0($$parsedSource["assetIds"]);
        }
        if ("timeline" in $$parsedSource) {
            $$parsedSource["timeline"] = $$createField3_0($$parsedSource["timeline"]);
        }
        return new EditProject($$parsedSource as Partial<EditProject>);
    }
}

/**
 * RenderJob tracks a single render job dispatched to the Azure Container App.
 */
export class RenderJob {
    "id": string;
    "projectId": string;
    "remoteJobId"?: string;
    "status": string;
    "outputUrl"?: string;
    "outputDriveItemId"?: string;
    "outputName"?: string;
    "percent": number;
    "currentMs": number;
    "totalMs": number;
    "message"?: string;
    "errorDetail"?: string;

    /** Creates a new RenderJob instance. */
    constructor($$source: Partial<RenderJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("currentMs" in $$source)) {
            this["currentMs"] = 0;
        }
        if (!("totalMs" in $$source)) {
            this["totalMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderJob instance from a string or object.
     */
    static createFrom($$source: any = {}): RenderJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenderJob($$parsedSource as Partial<RenderJob>);
    }
}

export class TextOverlay {
    "id": string;
    "text": string;
    "startMs": number;
    "endMs": number;

    /** Creates a new TextOverlay instance. */
    constructor($$source: Partial<TextOverlay> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextOverlay instance from a string or object.
     */
    static createFrom($$source: any = {}): TextOverlay {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextOverlay($$parsedSource as Partial<TextOverlay>);
    }
}

export class Timeline {
    "tracks": Track[];

    /** Creates a new Timeline instance. */
    constructor($$source: Partial<Timeline> = {}) {
        if (!("tracks" in $$source)) {
            this["tracks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Timeline instance from a string or object.
     */
    static createFrom($$source: any = {}): Timeline {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tracks" in $$parsedSource) {
            $$parsedSource["tracks"] = $$createField0_0($$parsedSource["tracks"]);
        }
        return new Timeline($$parsedSource as Partial<Timeline>);
    }
}

export class Track {
    "id": string;
    "kind": string;
    "clips": ClipSegment[];
    "overlays"?: TextOverlay[];

    /** Creates a new Track instance. */
    constructor($$source: Partial<Track> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("clips" in $$source)) {
            this["clips"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Track instance from a string or object.
     */
    static createFrom($$source: any = {}): Track {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clips" in $$parsedSource) {
            $$parsedSource["clips"] = $$createField2_0($$parsedSource["clips"]);
        }
        if ("overlays" in $$parsedSource) {
            $$parsedSource["overlays"] = $$createField3_0($$parsedSource["overlays"]);
        }
        return new Track($$parsedSource as Partial<Track>);
    }
}

export class Transition {
    "kind": string;
    "durationMs": number;

    /** Creates a new Transition instance. */
    constructor($$source: Partial<Transition> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Transition instance from a string or object.
     */
    static createFrom($$source: any = {}): Transition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Transition($$parsedSource as Partial<Transition>);
    }
}

// Private type creation functions
const $$createType0 = Transition.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Timeline.createFrom;
const $$createType4 = Track.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ClipSegment.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TextOverlay.createFrom;
const $$createType9 = $Create.Array($$createType8);
