// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BLEDevice {
    "id": string;
    "name": string;
    "model": string;
    "rssi": number;
    "address"?: string;
    "manufacturerDataHex"?: string;
    "serviceUuids"?: string[];
    "paired": boolean;
    "lastSeen"?: string;

    /** Creates a new BLEDevice instance. */
    constructor($$source: Partial<BLEDevice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("rssi" in $$source)) {
            this["rssi"] = 0;
        }
        if (!("paired" in $$source)) {
            this["paired"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BLEDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): BLEDevice {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serviceUuids" in $$parsedSource) {
            $$parsedSource["serviceUuids"] = $$createField6_0($$parsedSource["serviceUuids"]);
        }
        return new BLEDevice($$parsedSource as Partial<BLEDevice>);
    }
}

export class BLEProfile {
    "serviceUuid": string;
    "writeCharUuid": string;
    "pairingCharUuid": string;
    "statusCharUuid": string;
    "defaultPin": string;

    /** Creates a new BLEProfile instance. */
    constructor($$source: Partial<BLEProfile> = {}) {
        if (!("serviceUuid" in $$source)) {
            this["serviceUuid"] = "";
        }
        if (!("writeCharUuid" in $$source)) {
            this["writeCharUuid"] = "";
        }
        if (!("pairingCharUuid" in $$source)) {
            this["pairingCharUuid"] = "";
        }
        if (!("statusCharUuid" in $$source)) {
            this["statusCharUuid"] = "";
        }
        if (!("defaultPin" in $$source)) {
            this["defaultPin"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BLEProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): BLEProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BLEProfile($$parsedSource as Partial<BLEProfile>);
    }
}

export class ControlStatus {
    "bleAvailable": boolean;
    "wifiAvailable": boolean;
    "adapterConfigured": boolean;
    "bleAdapterName"?: string;
    "protocol": ProtocolProfile;
    "message": string;

    /** Creates a new ControlStatus instance. */
    constructor($$source: Partial<ControlStatus> = {}) {
        if (!("bleAvailable" in $$source)) {
            this["bleAvailable"] = false;
        }
        if (!("wifiAvailable" in $$source)) {
            this["wifiAvailable"] = false;
        }
        if (!("adapterConfigured" in $$source)) {
            this["adapterConfigured"] = false;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = (new ProtocolProfile());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControlStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ControlStatus {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("protocol" in $$parsedSource) {
            $$parsedSource["protocol"] = $$createField4_0($$parsedSource["protocol"]);
        }
        return new ControlStatus($$parsedSource as Partial<ControlStatus>);
    }
}

export class DUMLCommandDescriptor {
    "id": string;
    "label": string;
    "transport": string;
    "purpose": string;
    "source": string;
    "implemented": boolean;

    /** Creates a new DUMLCommandDescriptor instance. */
    constructor($$source: Partial<DUMLCommandDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("transport" in $$source)) {
            this["transport"] = "";
        }
        if (!("purpose" in $$source)) {
            this["purpose"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("implemented" in $$source)) {
            this["implemented"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DUMLCommandDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): DUMLCommandDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DUMLCommandDescriptor($$parsedSource as Partial<DUMLCommandDescriptor>);
    }
}

export class DiagnosticResult {
    "bleScanOk": boolean;
    "pairingOk": boolean;
    "wifiSetupOk": boolean;
    "udp9004Ok": boolean;
    "tcpMediaPortOk": boolean;
    "steps": DiagnosticStep[];
    "message": string;

    /** Creates a new DiagnosticResult instance. */
    constructor($$source: Partial<DiagnosticResult> = {}) {
        if (!("bleScanOk" in $$source)) {
            this["bleScanOk"] = false;
        }
        if (!("pairingOk" in $$source)) {
            this["pairingOk"] = false;
        }
        if (!("wifiSetupOk" in $$source)) {
            this["wifiSetupOk"] = false;
        }
        if (!("udp9004Ok" in $$source)) {
            this["udp9004Ok"] = false;
        }
        if (!("tcpMediaPortOk" in $$source)) {
            this["tcpMediaPortOk"] = false;
        }
        if (!("steps" in $$source)) {
            this["steps"] = [];
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticResult {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField5_0($$parsedSource["steps"]);
        }
        return new DiagnosticResult($$parsedSource as Partial<DiagnosticResult>);
    }
}

export class DiagnosticStep {
    "id": string;
    "label": string;
    "status": string;
    "transport"?: string;
    "description": string;

    /** Creates a new DiagnosticStep instance. */
    constructor($$source: Partial<DiagnosticStep> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticStep instance from a string or object.
     */
    static createFrom($$source: any = {}): DiagnosticStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticStep($$parsedSource as Partial<DiagnosticStep>);
    }
}

export class PairingRequest {
    "deviceId": string;
    "pin"?: string;

    /** Creates a new PairingRequest instance. */
    constructor($$source: Partial<PairingRequest> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PairingRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingRequest($$parsedSource as Partial<PairingRequest>);
    }
}

export class PairingResult {
    "deviceId"?: string;
    "paired": boolean;
    "requiresUserConfirmation": boolean;
    "message": string;

    /** Creates a new PairingResult instance. */
    constructor($$source: Partial<PairingResult> = {}) {
        if (!("paired" in $$source)) {
            this["paired"] = false;
        }
        if (!("requiresUserConfirmation" in $$source)) {
            this["requiresUserConfirmation"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PairingResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairingResult($$parsedSource as Partial<PairingResult>);
    }
}

export class ProtocolProfile {
    "modelHint": string;
    "ble": BLEProfile;
    "defaultIp": string;
    "mediaPorts": number[];
    "udpPort": number;
    "commandCatalog": DUMLCommandDescriptor[];
    "implementation": string;
    "referencePolicy": string;

    /** Creates a new ProtocolProfile instance. */
    constructor($$source: Partial<ProtocolProfile> = {}) {
        if (!("modelHint" in $$source)) {
            this["modelHint"] = "";
        }
        if (!("ble" in $$source)) {
            this["ble"] = (new BLEProfile());
        }
        if (!("defaultIp" in $$source)) {
            this["defaultIp"] = "";
        }
        if (!("mediaPorts" in $$source)) {
            this["mediaPorts"] = [];
        }
        if (!("udpPort" in $$source)) {
            this["udpPort"] = 0;
        }
        if (!("commandCatalog" in $$source)) {
            this["commandCatalog"] = [];
        }
        if (!("implementation" in $$source)) {
            this["implementation"] = "";
        }
        if (!("referencePolicy" in $$source)) {
            this["referencePolicy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtocolProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtocolProfile {
        const $$createField1_0 = $$createType4;
        const $$createField3_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ble" in $$parsedSource) {
            $$parsedSource["ble"] = $$createField1_0($$parsedSource["ble"]);
        }
        if ("mediaPorts" in $$parsedSource) {
            $$parsedSource["mediaPorts"] = $$createField3_0($$parsedSource["mediaPorts"]);
        }
        if ("commandCatalog" in $$parsedSource) {
            $$parsedSource["commandCatalog"] = $$createField5_0($$parsedSource["commandCatalog"]);
        }
        return new ProtocolProfile($$parsedSource as Partial<ProtocolProfile>);
    }
}

export class WiFiProfile {
    "ssid": string;
    "ipAddress": string;
    "gatewayIp"?: string;
    "port"?: number;
    "udpPort"?: number;
    "mediaPorts"?: number[];
    "message"?: string;

    /** Creates a new WiFiProfile instance. */
    constructor($$source: Partial<WiFiProfile> = {}) {
        if (!("ssid" in $$source)) {
            this["ssid"] = "";
        }
        if (!("ipAddress" in $$source)) {
            this["ipAddress"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WiFiProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): WiFiProfile {
        const $$createField5_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mediaPorts" in $$parsedSource) {
            $$parsedSource["mediaPorts"] = $$createField5_0($$parsedSource["mediaPorts"]);
        }
        return new WiFiProfile($$parsedSource as Partial<WiFiProfile>);
    }
}

export class WiFiSetupRequest {
    "deviceId": string;
    "ssid"?: string;

    /** Creates a new WiFiSetupRequest instance. */
    constructor($$source: Partial<WiFiSetupRequest> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WiFiSetupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): WiFiSetupRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WiFiSetupRequest($$parsedSource as Partial<WiFiSetupRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProtocolProfile.createFrom;
const $$createType2 = DiagnosticStep.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = BLEProfile.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = DUMLCommandDescriptor.createFrom;
const $$createType7 = $Create.Array($$createType6);
