// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AnalyzeHighlight describes a highlight candidate.
 */
export class AnalyzeHighlight {
    "id": string;
    "startMs": number;
    "endMs": number;
    "reason": string;
    "score": number;

    /** Creates a new AnalyzeHighlight instance. */
    constructor($$source: Partial<AnalyzeHighlight> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeHighlight instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeHighlight {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeHighlight($$parsedSource as Partial<AnalyzeHighlight>);
    }
}

/**
 * AnalyzeResult is the normalized analysis result returned by the media service.
 */
export class AnalyzeResult {
    "jobId": string;
    "status": string;
    "scenes": AnalyzeScene[];
    "transcript": AnalyzeTranscript[];
    "highlights": AnalyzeHighlight[];
    "suggestions": AnalyzeSuggestion[];

    /** Creates a new AnalyzeResult instance. */
    constructor($$source: Partial<AnalyzeResult> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("scenes" in $$source)) {
            this["scenes"] = [];
        }
        if (!("transcript" in $$source)) {
            this["transcript"] = [];
        }
        if (!("highlights" in $$source)) {
            this["highlights"] = [];
        }
        if (!("suggestions" in $$source)) {
            this["suggestions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeResult {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scenes" in $$parsedSource) {
            $$parsedSource["scenes"] = $$createField2_0($$parsedSource["scenes"]);
        }
        if ("transcript" in $$parsedSource) {
            $$parsedSource["transcript"] = $$createField3_0($$parsedSource["transcript"]);
        }
        if ("highlights" in $$parsedSource) {
            $$parsedSource["highlights"] = $$createField4_0($$parsedSource["highlights"]);
        }
        if ("suggestions" in $$parsedSource) {
            $$parsedSource["suggestions"] = $$createField5_0($$parsedSource["suggestions"]);
        }
        return new AnalyzeResult($$parsedSource as Partial<AnalyzeResult>);
    }
}

/**
 * AnalyzeScene describes a detected scene.
 */
export class AnalyzeScene {
    "id": string;
    "startMs": number;
    "endMs": number;
    "labels": string[];
    "summary"?: string;
    "highlight": boolean;

    /** Creates a new AnalyzeScene instance. */
    constructor($$source: Partial<AnalyzeScene> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("labels" in $$source)) {
            this["labels"] = [];
        }
        if (!("highlight" in $$source)) {
            this["highlight"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeScene instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeScene {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField3_0($$parsedSource["labels"]);
        }
        return new AnalyzeScene($$parsedSource as Partial<AnalyzeScene>);
    }
}

/**
 * AnalyzeSuggestion describes an edit suggestion.
 */
export class AnalyzeSuggestion {
    "id": string;
    "title": string;
    "description": string;
    "sceneIds": string[];

    /** Creates a new AnalyzeSuggestion instance. */
    constructor($$source: Partial<AnalyzeSuggestion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sceneIds" in $$source)) {
            this["sceneIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeSuggestion instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeSuggestion {
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sceneIds" in $$parsedSource) {
            $$parsedSource["sceneIds"] = $$createField3_0($$parsedSource["sceneIds"]);
        }
        return new AnalyzeSuggestion($$parsedSource as Partial<AnalyzeSuggestion>);
    }
}

/**
 * AnalyzeTranscript describes a transcript segment.
 */
export class AnalyzeTranscript {
    "startMs": number;
    "endMs": number;
    "text": string;
    "speaker"?: string;
    "score"?: number;

    /** Creates a new AnalyzeTranscript instance. */
    constructor($$source: Partial<AnalyzeTranscript> = {}) {
        if (!("startMs" in $$source)) {
            this["startMs"] = 0;
        }
        if (!("endMs" in $$source)) {
            this["endMs"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalyzeTranscript instance from a string or object.
     */
    static createFrom($$source: any = {}): AnalyzeTranscript {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalyzeTranscript($$parsedSource as Partial<AnalyzeTranscript>);
    }
}

// Private type creation functions
const $$createType0 = AnalyzeScene.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AnalyzeTranscript.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AnalyzeHighlight.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AnalyzeSuggestion.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
