// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DescribeLocalFilesRequest {
    "paths": string[];

    /** Creates a new DescribeLocalFilesRequest instance. */
    constructor($$source: Partial<DescribeLocalFilesRequest> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DescribeLocalFilesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DescribeLocalFilesRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DescribeLocalFilesRequest($$parsedSource as Partial<DescribeLocalFilesRequest>);
    }
}

export class LocalMediaFile {
    "id": string;
    "name": string;
    "path": string;
    "sizeBytes": number;
    "modifiedAt": string;
    "contentType"?: string;

    /** Creates a new LocalMediaFile instance. */
    constructor($$source: Partial<LocalMediaFile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalMediaFile instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalMediaFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalMediaFile($$parsedSource as Partial<LocalMediaFile>);
    }
}

export class LocalToOneDriveRequest {
    "files": LocalMediaFile[];
    "destinationPath": string;
    "chunkSizeBytes"?: number;

    /** Creates a new LocalToOneDriveRequest instance. */
    constructor($$source: Partial<LocalToOneDriveRequest> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("destinationPath" in $$source)) {
            this["destinationPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalToOneDriveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalToOneDriveRequest {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        return new LocalToOneDriveRequest($$parsedSource as Partial<LocalToOneDriveRequest>);
    }
}

export class StartTransferRequest {
    "cameraDeviceId": string;
    "mediaIds": string[];
    "destinationPath": string;

    /** Creates a new StartTransferRequest instance. */
    constructor($$source: Partial<StartTransferRequest> = {}) {
        if (!("cameraDeviceId" in $$source)) {
            this["cameraDeviceId"] = "";
        }
        if (!("mediaIds" in $$source)) {
            this["mediaIds"] = [];
        }
        if (!("destinationPath" in $$source)) {
            this["destinationPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartTransferRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartTransferRequest {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mediaIds" in $$parsedSource) {
            $$parsedSource["mediaIds"] = $$createField1_0($$parsedSource["mediaIds"]);
        }
        return new StartTransferRequest($$parsedSource as Partial<StartTransferRequest>);
    }
}

export class TransferJob {
    "id": string;
    "sourcePath": string;
    "destination": string;
    "status": TransferStatus;
    "bytesTotal": number;
    "bytesCompleted": number;
    "driveItemId"?: string;
    "fileName"?: string;
    "createdAt": string;
    "message"?: string;

    /** Creates a new TransferJob instance. */
    constructor($$source: Partial<TransferJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TransferStatus.$zero;
        }
        if (!("bytesTotal" in $$source)) {
            this["bytesTotal"] = 0;
        }
        if (!("bytesCompleted" in $$source)) {
            this["bytesCompleted"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferJob instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferJob($$parsedSource as Partial<TransferJob>);
    }
}

export enum TransferStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransferQueued = "queued",
    TransferRunning = "running",
    TransferCompleted = "completed",
    TransferBlocked = "blocked",
    TransferFailed = "failed",
    TransferCancelled = "cancelled",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = LocalMediaFile.createFrom;
const $$createType2 = $Create.Array($$createType1);
