// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contentunderstanding$0 from "../contentunderstanding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onedrive$0 from "../onedrive/models.js";

export class AppSettings {
    "tenantId"?: string;
    "clientId"?: string;
    "oneDriveFolder": string;
    "graphAuth": onedrive$0.GraphAuthConfig;
    "oneDriveDestination": onedrive$0.OneDriveDestination;
    "azureEndpoint"?: string;
    "azureAnalyzerId"?: string;
    "azureContentUnderstanding": contentunderstanding$0.Config;
    "ffmpegPath"?: string;
    "ffprobePath"?: string;
    "chunkSizeBytes": number;
    "maxConcurrentImports": number;
    "mediaServiceEndpoint"?: string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("oneDriveFolder" in $$source)) {
            this["oneDriveFolder"] = "";
        }
        if (!("graphAuth" in $$source)) {
            this["graphAuth"] = (new onedrive$0.GraphAuthConfig());
        }
        if (!("oneDriveDestination" in $$source)) {
            this["oneDriveDestination"] = (new onedrive$0.OneDriveDestination());
        }
        if (!("azureContentUnderstanding" in $$source)) {
            this["azureContentUnderstanding"] = (new contentunderstanding$0.Config());
        }
        if (!("chunkSizeBytes" in $$source)) {
            this["chunkSizeBytes"] = 0;
        }
        if (!("maxConcurrentImports" in $$source)) {
            this["maxConcurrentImports"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("graphAuth" in $$parsedSource) {
            $$parsedSource["graphAuth"] = $$createField3_0($$parsedSource["graphAuth"]);
        }
        if ("oneDriveDestination" in $$parsedSource) {
            $$parsedSource["oneDriveDestination"] = $$createField4_0($$parsedSource["oneDriveDestination"]);
        }
        if ("azureContentUnderstanding" in $$parsedSource) {
            $$parsedSource["azureContentUnderstanding"] = $$createField7_0($$parsedSource["azureContentUnderstanding"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

// Private type creation functions
const $$createType0 = onedrive$0.GraphAuthConfig.createFrom;
const $$createType1 = onedrive$0.OneDriveDestination.createFrom;
const $$createType2 = contentunderstanding$0.Config.createFrom;
