// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AuthFlow {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthFlowAuthorizationCodePKCE = "authorization_code_pkce",
    AuthFlowDeviceCode = "device_code",
};

export class AuthState {
    "status": AuthStatus;
    "accountName"?: string;
    "tenantId"?: string;
    "grantedScopes"?: string[];
    "tokenCacheAvailable": boolean;
    "expiresAt"?: string;
    "message"?: string;

    /** Creates a new AuthState instance. */
    constructor($$source: Partial<AuthState> = {}) {
        if (!("status" in $$source)) {
            this["status"] = AuthStatus.$zero;
        }
        if (!("tokenCacheAvailable" in $$source)) {
            this["tokenCacheAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthState instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthState {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("grantedScopes" in $$parsedSource) {
            $$parsedSource["grantedScopes"] = $$createField3_0($$parsedSource["grantedScopes"]);
        }
        return new AuthState($$parsedSource as Partial<AuthState>);
    }
}

export enum AuthStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthNotConfigured = "not_configured",
    AuthSignedOut = "signed_out",
    AuthSignedIn = "signed_in",
};

export class Client {
    "HTTPClient": HTTPClient;
    "TokenProvider": TokenProvider;
    "GraphBaseURL": string;
    "Scopes": string[];
    "Destination": OneDriveDestination;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("HTTPClient" in $$source)) {
            this["HTTPClient"] = null;
        }
        if (!("TokenProvider" in $$source)) {
            this["TokenProvider"] = null;
        }
        if (!("GraphBaseURL" in $$source)) {
            this["GraphBaseURL"] = "";
        }
        if (!("Scopes" in $$source)) {
            this["Scopes"] = [];
        }
        if (!("Destination" in $$source)) {
            this["Destination"] = (new OneDriveDestination());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Scopes" in $$parsedSource) {
            $$parsedSource["Scopes"] = $$createField3_0($$parsedSource["Scopes"]);
        }
        if ("Destination" in $$parsedSource) {
            $$parsedSource["Destination"] = $$createField4_0($$parsedSource["Destination"]);
        }
        return new Client($$parsedSource as Partial<Client>);
    }
}

export class DeviceCodeSession {
    "userCode": string;
    "verificationUri": string;
    "message": string;
    "expiresAt": string;
    "intervalSeconds": number;
    "tenantId": string;
    "clientId": string;
    "scopes": string[];

    /** Creates a new DeviceCodeSession instance. */
    constructor($$source: Partial<DeviceCodeSession> = {}) {
        if (!("userCode" in $$source)) {
            this["userCode"] = "";
        }
        if (!("verificationUri" in $$source)) {
            this["verificationUri"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("intervalSeconds" in $$source)) {
            this["intervalSeconds"] = 0;
        }
        if (!("tenantId" in $$source)) {
            this["tenantId"] = "";
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceCodeSession instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceCodeSession {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField7_0($$parsedSource["scopes"]);
        }
        return new DeviceCodeSession($$parsedSource as Partial<DeviceCodeSession>);
    }
}

export class GraphAuthConfig {
    "tenantId"?: string;
    "clientId"?: string;
    "redirectUri"?: string;
    "authFlow": AuthFlow;
    "scopes": string[];

    /** Creates a new GraphAuthConfig instance. */
    constructor($$source: Partial<GraphAuthConfig> = {}) {
        if (!("authFlow" in $$source)) {
            this["authFlow"] = AuthFlow.$zero;
        }
        if (!("scopes" in $$source)) {
            this["scopes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphAuthConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphAuthConfig {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField4_0($$parsedSource["scopes"]);
        }
        return new GraphAuthConfig($$parsedSource as Partial<GraphAuthConfig>);
    }
}

export type HTTPClient = any;

export class OneDriveDestination {
    "mode": string;
    "displayName": string;
    "path": string;
    "driveId"?: string;
    "driveItemId"?: string;

    /** Creates a new OneDriveDestination instance. */
    constructor($$source: Partial<OneDriveDestination> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OneDriveDestination instance from a string or object.
     */
    static createFrom($$source: any = {}): OneDriveDestination {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OneDriveDestination($$parsedSource as Partial<OneDriveDestination>);
    }
}

export class OneDriveUploadSession {
    "id": string;
    "driveItemId"?: string;
    "nextStart": number;
    "nextRanges"?: string[];
    "expiresAt"?: string;

    /** Creates a new OneDriveUploadSession instance. */
    constructor($$source: Partial<OneDriveUploadSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("nextStart" in $$source)) {
            this["nextStart"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OneDriveUploadSession instance from a string or object.
     */
    static createFrom($$source: any = {}): OneDriveUploadSession {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nextRanges" in $$parsedSource) {
            $$parsedSource["nextRanges"] = $$createField3_0($$parsedSource["nextRanges"]);
        }
        return new OneDriveUploadSession($$parsedSource as Partial<OneDriveUploadSession>);
    }
}

export class Status {
    "authStatus": AuthStatus;
    "scope": string;
    "scopes"?: string[];
    "auth": AuthState;
    "destination": OneDriveDestination;
    "message": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("authStatus" in $$source)) {
            this["authStatus"] = AuthStatus.$zero;
        }
        if (!("scope" in $$source)) {
            this["scope"] = "";
        }
        if (!("auth" in $$source)) {
            this["auth"] = (new AuthState());
        }
        if (!("destination" in $$source)) {
            this["destination"] = (new OneDriveDestination());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scopes" in $$parsedSource) {
            $$parsedSource["scopes"] = $$createField2_0($$parsedSource["scopes"]);
        }
        if ("auth" in $$parsedSource) {
            $$parsedSource["auth"] = $$createField3_0($$parsedSource["auth"]);
        }
        if ("destination" in $$parsedSource) {
            $$parsedSource["destination"] = $$createField4_0($$parsedSource["destination"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

export type TokenProvider = any;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = OneDriveDestination.createFrom;
const $$createType2 = AuthState.createFrom;
